### ISSUE TITLE
Replace user name with e-mail address

### ISSUE THREAD

**Issue by uklotzde** [kartevonmorgen/rfcs#5]
- RFC: https://github.com/kartevonmorgen/rfcs/blob/master/proposed/0000-replace-username-with-email.md
- Status: Proposed
- Time to start: Helmut suggests to wait till the new subscription process is working ( Issue from belarus https://github.com/diglabby/mapa/issues/6) Because this also affects the UI of login, subscription and useraccount-handling.

**Comment by wellemut** [comment]
# reset password not possible if two usernames for one mailadress (skip username)
See more on: https://github.com/kartevonmorgen/kartevonmorgen/issues/539#issuecomment-512275531

**Comment by flosse** [comment]
@wellemut can we accept this RFC?

**Comment by wellemut** [comment]
Yes we can!
(Only 11 users are affected. Just tell me, when I need to inform them. For for a certain while they would have to use a second mailadress to subscribe again, but soon the new subscription field will be availiable)

So lets Start!
